// vanilla mysql
// const db = require('../util/database');
// const Cart = require('./cart');

// module.exports = class Product {
// 	constructor(id, title, imageUrl, description, price) {
// 		this.id = id;
// 		this.title = title;
// 		this.imageUrl = imageUrl;
// 		this.description = description;
// 		this.price = price;
// 	}
// 	// reach to database and save there
// 	save() {
// 		// INSERT INTO, where we want to insert
// 		// () fields where we want to insert our data, they should match order just like in your database, id is generated by our db, we don't have to specify it
// 		// VALUES (?) what values we want to insert ? characters allow to insert data safely, preventing attacks on our database, ? prevent users from inserting special characters into input field
// 		// [] values that will be injected instead ????
// 		// ?? are basically a filter that values have to be passed through before they are inserted, this gives an extra layer of security

// 		// return the promise
// 		return db.execute(
// 			'INSERT INTO products (title, price, imageUrl, description) VALUES (?,?,?,?)',
// 			[this.title, this.price, this.imageUrl, this.description]
// 		);
// 	}

// 	static deleteById(id) {}

// 	static fetchAll() {
// 		// fetch all products
// 		return db.execute('SELECT * FROM products');
// 	}
// 	// find single product by id
// 	static findById(id) {
// 		// to restrict number of rows whe want to select we use WHERE
// 		return db.execute('SELECT * FROM products WHERE products.id = ?', [id]);
// 	}
// };

// sequelize
const Sequelize = require('sequelize');
const sequelize = require('../util/database');

// define a model that will be managed by sequelize
// (name, structure of a model)
const Product = sequelize.define('product', {
	// define fields our product should have
	id: {
		type: Sequelize.INTEGER,
		autoIncrement: true,
		allowNull: false,
		primaryKey: true,
	},
	title: {
		type: Sequelize.STRING,
		allowNull: false,
	},
	price: {
		type: Sequelize.DOUBLE,
		allowNull: false,
	},
	imageUrl: {
		type: Sequelize.STRING,
		allowNull: false,
	},
	description: {
		type: Sequelize.STRING,
		allowNull: false,
	},
});

module.exports = Product;
